/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include<FreeRTOS.h>
#include<FreeRTOSConfig.h>
#include<task.h>
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vAperiodicTask1(void *pvParam)
{
   for( ; ;){
	   led_toggle(LED_GREEN);
	   vTaskDelay(1000/portTICK_RATE_MS);
   }
   vTaskDelete(NULL);
}

void vperiodicTask2(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
   for( ; ;){
	   led_toggle(LED_ORANGE);
	   vTaskDelayUntil(&pxPreviousWakeUpTime,3000/portTICK_RATE_MS);
   }
   vTaskDelete(NULL);
}

void vAperiodicTask3(void *pvParam)
{
   for( ; ;){

	   led_toggle(LED_RED);
	   vTaskDelay(2000/portTICK_RATE_MS);
   }
   vTaskDelete(NULL);
}

void vperiodicTask4(void *pvParam)
{
	portTickType pxPreviousWakeUpTime = xTaskGetTickCount();
   for( ; ;){
	   led_toggle(LED_BLUE);
	   vTaskDelayUntil(&pxPreviousWakeUpTime,4000/portTICK_RATE_MS);
   }
   vTaskDelete(NULL);
}


int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);

   xTaskCreate(vAperiodicTask1,"Task1",configMINIMAL_STACK_SIZE,NULL,4,NULL);
   xTaskCreate(vperiodicTask2,"Task2",configMINIMAL_STACK_SIZE,NULL,4,NULL);
   xTaskCreate(vAperiodicTask3,"Task3",configMINIMAL_STACK_SIZE,NULL,4,NULL);
   xTaskCreate(vperiodicTask4,"Task4",configMINIMAL_STACK_SIZE,NULL,4,NULL);


   vTaskStartScheduler();

   while(1);
}
